### ISSUE TITLE
Command Line Interface

### ISSUE THREAD

**Issue by JacobAMason** [JacobAMason/Software-Testing-and-QA#1]
Develop a command line app that prompts the user to select a function to execute and allows the user to gracefully exit the app when desired. The menu should be displayed after each function (although a GUI is not required, you are permitted to create one) unless the user exits.

**Comment by EliCDavis** [comment]
So is a command line version *required* or can it be completely replaced by a GUI?  I've wanted to learn a Python GUI framework

**Comment by JacobAMason** [comment]
That's a good question for Dr. Byron.

**Comment by EliCDavis** [comment]
When asking Byron, he said CLI can be completely replaced with a GUI

**Comment by EliCDavis** [comment]
Wonder if we could do a small server that would host a webpage for a GUI 😏

**Comment by JacobAMason** [comment]
We could. It might be faster than writing one in python

**Comment by EliCDavis** [comment]
I am currently messing with tkinter.  I do not think it will be hard with what limited functionality our project has, but I am not sure of the best way to test this, or if it even needs to be tested.

**Comment by JacobAMason** [comment]
It is possible to test tkinter code, just not easily as tkinter was made before tdd was a thing (http://code.activestate.com/recipes/578964-robust-testing-of-tkinter-menu-items-with-mocking/)

**Comment by EliCDavis** [comment]
Huh, that's looks gross.  If we don't have to test the GUI I'll build it, else I can just build the CLI
