### ISSUE TITLE
Screencast - Evidence of TDD Process

### ISSUE THREAD

**Issue by JacobAMason** [JacobAMason/Software-Testing-and-QA#15]
- [x] ~~Setup Snagit (http://www.its.msstate.edu/software/downloads/) - MSU provides license or LiceCap (http://www.cockos.com/licecap/) - open source~~ Use existing software
- [x] Record screencast of the red, green, refactor process (no sound required)
- [x] Prior to recording, complete initial test fixture setup and several unit tests with associated implementations (i.e., you should have completed several RGR iterations with some functional code previously implemented).
- [x] Record up to 4 minutes of desktop (IDE / Editor / Terminal) + test runner output that shows at least 2 RGR steps:
1. Write a test - watch it fail
2. Write code so that the test passes
3. Refactor (optional - as needed)
- [x] Repeat at least once 
- [x] Objective is to show process conformance 
- [x] Record execution of 2 functions in the working program (1 minute max video)
- [x] Show the program’s initial screen, select a function, provide input, execute and return
- [x] Upload screencasts to ~~GitHub Repo~~ YouTube for submission

**Comment by JacobAMason** [comment]
I don't have a Windows machine and this would be a pain for me to do.

**Comment by RickArendall** [comment]
I can do the red-green-refactor part of this later today if no one else already has and you don't mind it being a little sparse. I would roll back the distance formula branch temporarily on my local machine and just go all school demo-ey with showing the last few steps to get a couple of RGF cycles

**Comment by JacobAMason** [comment]
@RickArendall That'd be great

**Comment by EliCDavis** [comment]
Videos:
https://www.youtube.com/watch?v=Ldrxn17MOx4
https://www.youtube.com/watch?v=jJ3Do05n2mA
