### ISSUE TITLE
Select naming and organizational conventions

### ISSUE THREAD

**Issue by JacobAMason** [JacobAMason/Software-Testing-and-QA#7]
Determine (based on the framework / language selected) how you will name and organize your unit tests. Write a brief summary (in prose) of the organization to include: how will the tests be organized (e.g., folder structure, test sets/suites, groupings); how will you name the tests (each test and test set should describe what is being tested - either in the name or using a message passed upon success / fail),  how will you determine if testing is adequate, etc.

**Comment by EliCDavis** [comment]
Copy+Paste PEP8?
